import{a as p,S as L,i as u}from"./assets/vendor-D73Uttp0.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const m=r=>`<li class="gallery-card">
        <a href="${r.largeImageURL}">
            <img class="gallery-img" src="${r.webformatURL}" alt="${r.tags}" />
        </a>
        <div class="gallery-info">
            <p><b>Likes:</b> ${r.likes}</p>
            <p><b>Views:</b> ${r.views}</p>
            <p><b>Comments:</b> ${r.comments}</p>
            <p><b>Downloads:</b> ${r.downloads}</p>
        </div>
    </li>`;p.defaults.baseURL="https://pixabay.com";const y=async(r,e)=>{const o={params:{q:r,image_type:"photos",orientation:"horizontal",safesearch:!0,key:"46112845-f959e042da8238bb9faecb37a",per_page:15,page:e}};return(await p.get("/api/",o)).data};document.querySelector(".main-button");const f=document.querySelector(".main-form"),v=document.querySelector(".main-input"),l=document.querySelector(".js-list"),a=document.querySelector(".js-load-more"),h=document.querySelector(".loader"),g=new L(".gallery-card a",{captionsData:"alt",captionDelay:250});let i=1,c="",b=0;const w=async r=>{if(r.preventDefault(),l.innerHTML="",c=v.value.trim(),i=1,c==="")return u.show({message:"Please fill out the form!",position:"topRight",color:"red"});h.classList.remove("is-hidden");try{const e=await y(c,i);if(e.hits.length===0)return a.classList.add("is-hidden"),u.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",color:"red"});const o=e.hits.map(m).join("");l.innerHTML=o,b=l.querySelector("li").getBoundingClientRect().height,g.refresh(),e.hits.length<15?a.classList.add("is-hidden"):a.classList.remove("is-hidden")}catch(e){console.log(e)}finally{h.classList.add("is-hidden"),f.reset()}},S=async r=>{try{i++;const e=await y(c,i),o=e.hits.map(m).join("");l.insertAdjacentHTML("beforeend",o),g.refresh(),scrollBy({top:b*2,behavior:"smooth"}),(e.hits.length<15||i*15>=e.totalHits)&&(a.classList.add("is-hidden"),u.show({message:"We're sorry, but you've reached the end of search results.",position:"topRight",color:"blue"}))}catch(e){console.log(e)}};f.addEventListener("submit",w);a.addEventListener("click",S);
//# sourceMappingURL=index.js.map
